environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"

platform:
  - x64

install:
  # Get the latest stable version of Node.js or io.js
  - ps: |
      try {
      Install-Product node $env:nodejs_version $env:platform
      } catch {
      echo "Unable to install node $env:nodejs_version, trying update..."
      Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
      }
  # install modules
  - npm config set loglevel warn
  - npm i -g npm
  - npm ci

test_script:
  - npm run lint
  - npm test

build: off
